guonaihong/gout

README.md, group.go, group_test.go
=> done #33 修改API名字

gout.go
=> done #39, add Def function

README.md, gout.go, gout_test.go, group.go
#46 新增包级别method函数
```go
package main
import (
"github.com/guonaihong/gout"
)
func main() {
gout.POST(url).Do()
gout.GET(url).Do()
gout.DELETE(url).Do()
gout.DELETE(url).Do()
gout.PATCH(url).Do()
gout.HEAD(url).Do()
gout.OPTIONS(url).Do()
}
```
=> done #46, 完成顶层GET, POST 等方法

README.md, form-xxx-to-gout-doc/beego-httplib.md, utils.go
=> Httplib doc

README.md, context_test.go, group.go, group_test.go, req.go
#52 
1. 新增WithContext以及测试代码
2. 完善context_test.go测试代码
=> 完成#52。新增WithContext函数

README.md, decode/body.go, decode/body_test.go, group.go, group_test.go
支持unix domain socket #54
1. 新增UnixSocket函数
2. 增加domain socket 测试用例
3. 增加body_test.go
=> Unix socket 54

core/core.go, decode/body_test.go, decode/json.go, decode/json_test.go, decode/xml.go, decode/xml_test.go, decode/yaml.go, decode/yaml_test.go, encode/body_test.go, encode/json.go, encode/json_test.go, encode/xml.go, encode/xml_test.go, encode/yaml.go, encode/yaml_test.go, group.go
=> Cover test 56

README.md
=> Redact Document

README.md
=> 新增http2文档 #53

README.md, debug.go, debug_test.go, gout.go, group.go, req.go, utils.go
#55  支持debug模式
使用Debug(true)函数打开该功能
=> Debug mode

README.md, from-xxx-to-gout-doc/resty-doc.md
#58 
主要对比
* http header
* query
* json
* string
=> 新增和resty的对比文档

README.md
=> 优化文档，突出特色功能 #72

context_test.go, core/core.go, debug.go, encode/encode_core.go, encode/encode_core_test.go, encode/form.go, encode/form_test.go, encode/header_test.go, encode/json_test.go, encode/xml_test.go, encode/yaml_test.go, gout_test.go, group.go, group_test.go, req.go, req_test.go, utils.go, utils_test.go
=> 提升代码覆盖度到80%

README.md
=> 修改callback demo #75

README.md, debug.go
=> Quick start

decode/decode_core.go, decode/decode_core_test.go, decode/header_test.go
=> fix: BindHeader see #107

color/color.go, color/color_test.go, debug.go, group_test.go
=> change debug

README.md
=> Doc add feature

dataflow.go, dataflow_test.go
see #146  
修改debug(false)会输出debug信息的现象。
=> fix debug不一致的地方

dataflow.go, dataflow_test.go, req.go
=> 新增SetURL函数

Makefile, README.md, _example/17a-import-rawhttp.go, _example/go.mod, bench_test.go, dataflow.go, dataflow_test.go, debug.go, gout.go, import.go, import_rawtext.go, import_rawtext_test.go, req.go, retry_test.go, testdata/raw-http-post-formdata.txt, testdata/raw-http-post-json.txt
=> Import text

README.md, _example/17a-import-rawhttp.go, dataflow.go, dataflow_test.go, import.go, import_rawtext_test.go, req.go, retry_test.go, version.go
=> 新增SetHost函数

README.md, _example/18a-gen-curl.go, curl.go, curl_test.go, dataflow.go, encode/form_test.go, encode/json.go, encode/json_test.go, export.go, export/curl.go, export/curl_test.go, export/curl_tmpl.go, req.go, retry.go
#138 生成curl命令
```go
package main
import (
"fmt"
"github.com/guonaihong/gout"
)
func main() {
// 1.formdata
err := gout.GET(":1234").
SetForm(gout.A{"text", "good", "mode", "A", "voice", gout.FormFile("./t8.go")}).
Export().Curl().Do()
// output:
// curl -X GET -F "text=good" -F "mode=A" -F "voice=@./voice" "http://127.0.0.1:1234"
// 2.json body
err = gout.GET(":1234").
SetJSON(gout.H{"key1": "val1", "key2": "val2"}).
Export().Curl().Do()
// output:
// curl -X GET -H "Content-Type:application/json" -d "{\"key1\":\"val1\",\"key2\":\"val2\"}" "http://127.0.0.1:1234"
fmt.Printf("%v\n", err)
}
```
=> Generate curl

README.md, _example/go.mod
=> modify doc

README.md
=> 更新构架图，新增import和export等概念

core/test.go, dataflow/dataflow.go, dataflow/dataflow_test.go
=> 新增GetHost接口

dataflow/context_test.go, dataflow/dataflow_test.go, dataflow/req.go, filter/retry_test.go
=> 忽略io.EOF错误

dataflow/dataflow.go, dataflow/dataflow_test.go, gout_test.go
=> 新增SetMethod函数

core/core.go, core/core_test.go, dataflow/dataflow.go, dataflow/dataflow_test.go, dataflow/req.go, dataflow/req_test.go
=> SetQuery支持[]byte类型

_example/02-query.go, _example/go.mod, _example/go.sum, dataflow/dataflow.go, decode/header_test.go, go.mod
=> BindHeader新增slice类型测试代码

dataflow/dataflow_test.go, dataflow/req.go, import_rawtext_test.go
=> 新增Request测试代码

dataflow/dataflow_header_test.go, dataflow/dataflow_test.go, encode/encode_core.go, encode/encode_core_test.go
=> update #202 ，如果SetHeader传递的数据为空，忽略错误

dataflow/dataflow_test.go, dataflow/debug.go, dataflow/debug_test.go
=> 修复 打开debug模式，有些情部不会输出request body的信息

dataflow/dataflow.go, dataflow/dataflow_test.go, dataflow/dataflow_wwwform_test.go, dataflow/req.go, dataflow/req_test.go, encode/www_form.go, encode/www_form_test.go
=> SetWWWForm支持多参数

color/color.go, color/color_test.go, dataflow/debug.go, dataflow/debug_test.go, version.go
=> 修改debug模式，http header里面有%号不会显示奇怪的信息

bench/report.go
=> 解决在32位下编译出现overflows int问题

encode/form.go, encode/form_test.go, testdata/test.pcm
=> 调整FormFile和FormType的优先级

.github/workflows/go.yml, dataflow/dataflow_header_test.go, decode/decode_core_test.go, encode/query_test.go, filter/retry.go, filter/retry_test.go, version.go
=> 386 bug overflow

LICENSE, README.md, dataflow/dataflow.go, dataflow/global_config.go, dataflow/req.go, encode/query.go, encode/query_test.go, encode/www_form.go, encode/www_form_test.go, gout.go, query_test.go, setting/setting.go, version.go
=> Not ignore empty

README.md, dataflow/dataflow.go, dataflow/req.go, gout.go, setting/setting.go, timeout_test.go, version.go
=> 新增SetTimeout全局配置

bench/report.go, dataflow/dataflow_body_test.go, dataflow/dataflow_form_test.go, dataflow/dataflow_test.go, export/curl_core_test.go
=> fix the issues in goreportcard

README.md, dataflow/dataflow.go, dataflow/req.go, gout_chunked_test.go, setting/setting.go
=> 实现#283 , 新加Chunked()接口

README.md, dataflow/dataflow.go, dataflow/gout.go, dataflow/req.go, dataflow/req_basic_auth_test.go, version.go
=> Basic auth

README.md, dataflow/dataflow_query_test.go, dataflow/dataflow_wwwform_test.go, dataflow/global_config.go, query_test.go
默认不忽略空值, 如果在结构体里面想忽略空值, 加上omitempty tag就行.
=> Null values not ignored default

README.md, decode/header.go, decode/header_test.go, version.go
=> 增强BindHeader接口

dataflow/utils.go, dataflow/utils_test.go
query 内容被改变
```
gout.POST("https://www.aa.com/urls?site=https://bb.com").Debug(true).Do()
```
```
> POST /urls?site=https:/bb.com HTTP/1.1
>
```
=> fix: path.Clean 后query内容改变

README.md, dataflow/dataflow.go, dataflow/dataflow_middleware_test.go, dataflow/req.go, go.mod, interface/response_use_interface.go
=> response拦截器（中间件）

README.md, interface/request_use_interface.go, interface/response_use_interface.go
创建middleware 的wrapper helper，如果只需要闭包内逻辑，可以不用再创建一个没用的结构体
=> add middleware helper

dataflow/dataflow_form_test.go, dataflow/dataflow_test.go, encode/encode_core.go, encode/encode_core_test.go
=> 完善#322, API表现更符合直觉

README.md, dataflow/dataflow.go, dataflow/dataflow_body_test.go, dataflow/debug.go, dataflow/req.go, version.go
=> Set xxx ex

.github/workflows/go.yml, README.md, dataflow/dataflow.go, dataflow/gout.go, dataflow/req.go, dataflow/req_bench_test.go, dataflow/req_url_template_test.go, gout.go
=> Url support template

debug/api.go, debug/debug.go, debug/debug_trace.go, trace_test.go
=> 完成issue377
